version: "1"
services:
  app:
    image: node:5.10.1
    ports:
      - 8888:8888
    command: ["node", "/src/app.js"]
    links:
      - redis

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

registries: {}
