# This should be your Ansible playbooks to provision your containers.
# An inventory will be automatically created using the names of the services
# from your container.yml file.
# Add any roles or other modules you'll need to this directory too.
# For many examples of roles, check out Ansible Galaxy: https://galaxy.ansible.com/

- hosts: all
  gather_facts: false
  tasks:
    - name: check for python
      raw: which python || true
      register: which_python_results

    - name: ansible requires python
      raw: (which python) || (apt-get update && apt-get install -y --no-install-recommends python)
      when: "'python' not in which_python_results.stdout"

- hosts: all
  strategy: free
  vars:
    dumb_init_version: 1.1.3
    jenkins_hostname: localhost
    jenkins_home: /var/lib/jenkins
    jenkins_plugins:
      - git
      - swarm
      - workflow-aggregator
      - AnsiColor
    jenkins_ci_repo_url: https://repo.jenkins-ci.org/releases
    jenkins_swarm_client_version: 2.2
    jenkins_swarm_client_jar_name: swarm-client-{{jenkins_swarm_client_version}}-jar-with-dependencies.jar
    jenkins_swarm_client_jar_url: "{{jenkins_ci_repo_url}}/org/jenkins-ci/plugins/swarm-client/{{jenkins_swarm_client_version}}/{{jenkins_swarm_client_jar_name}}"

  pre_tasks:
    - name: install ansible role dependency packages
      apt:
        name: "{{item}}"
        state: present
      with_items:
        - sudo
        - make

    - name: install build-essential to build ruby from source
      apt:
        name: build-essential
        state: present
      when: "'ruby' in inventory_hostname"

  roles:
    - role: docker

    - role: ansible-container

    - role: geerlingguy.jenkins
      java_packages:
        - openjdk-8-jre-headless
      when: inventory_hostname == 'master'

    - role: geerlingguy.nodejs
      ansible_user: root
      nodejs_version: 0.12
      when: inventory_hostname == 'slave-nodejs012'

    - role: geerlingguy.nodejs
      ansible_user: root
      nodejs_version: 4.x
      when: inventory_hostname == 'slave-nodejs4x'

    - role: geerlingguy.ruby
      ansible_ssh_user: root
      ruby_install_from_source: yes
      ruby_download_url: http://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.5.tar.gz
      ruby_version: 2.2.5
      when: inventory_hostname == 'slave-ruby22'

    - role: geerlingguy.ruby
      ansible_ssh_user: root
      ruby_install_from_source: yes
      ruby_download_url: http://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.1.tar.gz
      ruby_version: 2.3.1
      when: inventory_hostname == 'slave-ruby23'

  tasks:
    - name: dropin custom jenkins startup scripts
      copy:
        src: "{{item}}"
        dest: "{{jenkins_home}}/init.groovy.d/{{item}}"
        mode: 0755
        owner: jenkins
        group: jenkins
      with_items:
        - tcp-slave-agent-port.groovy
      notify: restart jenkins
      when: inventory_hostname == 'master'

    - name: install dumb init
      get_url:
        dest: /usr/bin/dumb-init
        url: https://github.com/Yelp/dumb-init/releases/download/v{{dumb_init_version}}/dumb-init_{{dumb_init_version}}_amd64
        mode: 0755

    - name: download jenkins swarm
      get_url:
        dest: /opt/swarm-client.jar
        url: "{{jenkins_swarm_client_jar_url}}"
        mode: 0755
      when: "'slave' in inventory_hostname"
